### ISSUE TITLE
Service Feature Management problems

### ISSUE THREAD

**Issue by raoulhentschel** [SebLeich/broker-client#18] opened 2020-02-07 13:57 UTC
The new service management features (e.g. Zertifikate, Datenspeicherorte) are visible but not clickable.
![image](https://user-images.githubusercontent.com/54834712/74035238-3333d100-49ba-11ea-9f1c-7f8694604c6a.png)

**Comment by SebLeich** [comment] 2020-03-04 13:05
These functions are currently not implemented. We need further enhancements to provide them.

**Comment by SebLeich** [comment] 2020-03-04 13:32
Duplicate of #13

**Closed** 2020-09-03 12:27 UTC
Labels: enhancement
